local utils = require('utils')

vim.g.mapleader = ' '

utils.map('n', '[bookmark]', '<Nop>', { silent = false })
utils.map('n', '[buffer]',   '<Nop>', { silent = false })
utils.map('n', '[execute]',  '<Nop>', { silent = false })
utils.map('n', '[file]',     '<Nop>', { silent = false })
utils.map('n', '[git]',      '<Nop>', { silent = false })
utils.map('n', '[project]',  '<Nop>', { silent = false })
utils.map('n', '[language]', '<Nop>', { silent = false })
utils.map('n', '[quit]',     '<Nop>', { silent = false })
utils.map('n', '[search]',   '<Nop>', { silent = false })

utils.map('n', '<leader>b', '[buffer]',   { noremap = false, silent = false })
utils.map('n', '<leader>f', '[file]',     { noremap = false, silent = false })
utils.map('n', '<leader>g', '[git]',      { noremap = false, silent = false })
utils.map('n', '<leader>l', '[language]', { noremap = false, silent = false })
utils.map('n', '<leader>m', '[bookmark]', { noremap = false, silent = false })
utils.map('n', '<leader>p', '[project]',  { noremap = false, silent = false })
utils.map('n', '<leader>q', '[quit]',     { noremap = false, silent = false })
utils.map('n', '<leader>s', '[search]',   { noremap = false, silent = false })
utils.map('n', '<leader>x', '[execute]',  { noremap = false, silent = false })

utils.map('n', '<Esc><Esc>', ':nohlsearch<CR><Esc>')
utils.map('n', 's',          '<Nop>')
utils.map('n', 's/',         ':<C-u>vs<CR><C-w>l')
utils.map('n', 's-',         ':<C-u>sp<CR><C-w>j')
utils.map('n', 'sc',         '<C-w>c')
utils.map('n', 'sd',         '<C-w>c')
utils.map('n', 'sh',         '<C-w>h')
utils.map('n', 'sj',         '<C-w>j')
utils.map('n', 'sk',         '<C-w>k')
utils.map('n', 'sl',         '<C-w>l')
utils.map('n', 'so',         '<C-w>o')
utils.map('n', 'ss',         '<C-w>s')
utils.map('n', 'x',          '"_x')
utils.map('n', 'D',          '"_D')
utils.map('n', '[buffer]d',  ':<C-u>bw<CR>')
utils.map('n', '[buffer]n',  ':<C-u>bn<CR>')
utils.map('n', '[buffer]p',  ':<C-u>bp<CR>')
utils.map('n', '[execute]s', ':<C-u>term<CR>')
utils.map('n', '[file]s',    ':<C-u>w<CR>')
utils.map('n', '[quit]Q',    ':qall!<CR>')
utils.map('n', '[quit]q',    ':wqall<CR>')

utils.map('i', 'jk',         '<Esc>')

utils.map('t', '<C-g>',      '<C-\\><C-n>')
