local utils = require('utils')

utils.option('o', 'clipboard',      'unnamed,unnamedplus')
utils.option('o', 'cmdheight',      2)
utils.option('o', 'completeopt',    'menuone,noinsert,noselect')
utils.option('o', 'fileencodings',  'ucs-bombs,utf-8,euc-jp,cp932')
utils.option('o', 'fileformats',    'unix,mac,dos')
utils.option('o', 'guicursor',      '')
utils.option('o', 'hidden',         true)
utils.option('o', 'ignorecase',     true)
utils.option('o', 'laststatus',     2)
utils.option('o', 'mouse',          'a')
utils.option('o', 'pumblend',       10)
utils.option('o', 'scrolloff',      5)
utils.option('o', 'showmode',       false)
utils.option('o', 'smartcase',      true)
utils.option('o', 'termguicolors',  true)
utils.option('o', 'timeoutlen',     1000)
utils.option('o', 'ttimeoutlen',    1)
utils.option('o', 'updatetime',     200)
utils.option('o', 'visualbell',     true)
utils.option('o', 'whichwrap',      'b,s,<,>,[,]')
utils.option('o', 'winblend',       10)
utils.option('o', 'wrapscan',       true)

utils.option('w', 'cursorline',     true)
utils.option('w', 'list',           true)
utils.option('w', 'listchars',      'tab:» ,trail:-')
utils.option('w', 'number',         true)
utils.option('w', 'numberwidth',    5)
utils.option('w', 'relativenumber', true)
utils.option('w', 'signcolumn',     'yes')

utils.option('b', 'expandtab',      true)
utils.option('b', 'shiftwidth',     2)
utils.option('b', 'smartindent',    true)
utils.option('b', 'softtabstop',    2)
utils.option('b', 'swapfile',       false)
utils.option('b', 'tabstop',        2)
utils.option('b', 'tabstop',        2)

vim.cmd('set shortmess+=c')
